### ISSUE TITLE
[Suggestion] Bundle in "Freeze Challenge Timer" Code

### ISSUE THREAD

**Issue by RagdollClash** [GenerationsSM64/GenerationsSM64#4]
Given how slow Mario is compared to Sonic, this ends up making a few challenges hard if not impossible to beat within their time limits. Adding this code will allow the opportunity for those challenges to be beaten by Mario.

**Comment by GenerationsSM64** [comment]
Implemented in [c1d34f0](https://github.com/GenerationsSM64/GenerationsSM64/commit/c1d34f057f07b90f782a46beb8f3128f7f69ea6c)
